class Lesson {
  final int id;
  final String level;
  final String title;
  final List<List<String>> vocab;
  final Map<String, dynamic> reading;
  final String listening;
  final String writing;
  final String writingSample;
  final String speaking;
  final String grammar;

  const Lesson({
    required this.id,
    required this.level,
    required this.title,
    required this.vocab,
    required this.reading,
    required this.listening,
    required this.writing,
    required this.writingSample,
    required this.speaking,
    required this.grammar,
  });
}

class LessonData {
  static const List<Lesson> lessons = [
    // A0 Level
    Lesson(
      id: 1,
      level: 'A0',
      title: 'Salomlashish va Tanishuv',
      vocab: [
        ['Hello', 'Salom'],
        ['Good morning', 'Erta tong'],
        ['Goodbye', 'Xayr'],
        ['Name', 'Ism'],
        ['My name is', 'Mening ismim'],
        ['I am', 'Men'],
        ['You are', 'Siz'],
        ['Nice to meet you', 'Tanishganimdan xursandman'],
        ['What is your name?', 'Ismingiz nima?'],
        ['How are you?', 'Qandaysiniz?'],
        ["I'm fine", 'Yaxshiman'],
        ['Thank you', 'Rahmat'],
        ['Please', 'Iltimos'],
        ['Sorry', 'Kechirasiz'],
        ['Yes', 'Ha'],
        ['No', "Yo'q"],
        ['From', '...dan'],
        ['This is', 'Bu'],
        ['My friend', "Mening do'stim"],
        ['Teacher', "O'qituvchi"],
        ['Student', 'Talaba'],
        ['Learn', "O'rganmoq"],
        ['Speak', 'Gapirmoq'],
        ['Help', 'Yordam'],
        ['Welcome', 'Xush kelibsiz'],
      ],
      reading: {
        't': 'Alex: Hello! My name is Alex.\nSarah: Hi! I am Sarah. Nice to meet you.\nAlex: Nice to meet you too! Are you from Tashkent?\nSarah: Yes, I am. And you?\nAlex: I am from Samarkand.',
        'q': "Sarahlardan kim Toshkentdan?",
        'o': ['Alex', 'Sarah', 'Tom', 'David'],
        'c': 1,
      },
      listening: 'Hello, my name is Alex. Nice to meet you.',
      writing: 'Salom! Mening ismim ...',
      writingSample: 'Hello! My name is ...',
      speaking: 'Introduce yourself.',
      grammar: 'Ism - Name | Salomlashish - Greetings | Rahmat - Thank you',
    ),
    Lesson(
      id: 2,
      level: 'A0',
      title: 'Raqamlar va Yosh',
      vocab: [
        ['One', 'Bir'],
        ['Two', 'Ikki'],
        ['Three', 'Uch'],
        ['Four', "To'rt"],
        ['Five', 'Besh'],
        ['Six', 'Olti'],
        ['Seven', 'Yetti'],
        ['Eight', 'Sakkiz'],
        ['Nine', "To'qqiz"],
        ['Ten', "O'n"],
        ['Twenty', 'Yigirma'],
        ['Thirty', "O'ttiz"],
        ['Hundred', 'Yuz'],
        ['Years old', 'Yoshda'],
        ['Student', 'Talaba'],
        ["Teacher", "O'qituvchi"],
        ['Doctor', 'Shifokor'],
        ['Old', 'Katta'],
        ['Young', 'Yosh'],
        ['First', 'Birinchi'],
        ['Second', 'Ikkinchi'],
        ['Third', 'Uchinchi'],
        ['Number', 'Raqam'],
        ['Age', 'Yosh'],
        ['Birthday', "Tug'ilgan kun"],
      ],
      reading: {
        't': 'Anna is twenty-five. She is a teacher.\nMark is thirty. He is an engineer.\nThey are at school.',
        'q': 'Anna necha yoshda?',
        'o': ['5', '20', '25', '30'],
        'c': 2,
      },
      listening: 'I am twenty-five years old.',
      writing: 'Men 18 yoshdaman.',
      writingSample: 'I am 18 years old.',
      speaking: 'Say your age and job.',
      grammar: 'Raqamlar - Numbers | Yosh - Age',
    ),
    Lesson(
      id: 3,
      level: 'A0',
      title: 'Oila va Qarindoshlar',
      vocab: [
        ['Father', 'Ota'],
        ['Mother', 'Ona'],
        ['Brother', 'Aka'],
        ['Sister', 'Opa'],
        ['Family', 'Oila'],
        ['Grandfather', 'Katta ota'],
        ['Grandmother', 'Katta ona'],
        ["Son", "O'g'il"],
        ['Daughter', 'Qiz'],
        ['Husband', 'Er'],
        ['Wife', 'Xotin'],
        ['Uncle', 'Amaki'],
        ['Aunt', 'Tegishli'],
        ['Cousin', 'Jiyana'],
        ['Love', 'Sevmoq'],
        ['Big', 'Katta'],
        ['Small', 'Kichik'],
        ['I have', 'Mening bor'],
        ['Parents', 'Ota-onalar'],
        ['Baby', 'Chaqaloq'],
        ['Young', 'Yosh'],
        ['Old', 'Katta'],
        ['Together', 'Birga'],
        ['Home', 'Uy'],
        ['Happy', 'Baxtli'],
      ],
      reading: {
        't': 'I have a big family.\nMy father is a doctor.\nMy mother is a teacher.\nI have one brother and one sister.',
        'q': "Onasi nima qiladi?",
        'o': ['Doctor', 'Driver', 'Teacher', 'Engineer'],
        'c': 2,
      },
      listening: 'My father is a doctor.',
      writing: "Mening otam shifokor.",
      writingSample: 'My father is a doctor.',
      speaking: 'Talk about your family.',
      grammar: 'Oila - Family | Ota - Father | Ona - Mother',
    ),
    // A1 Level
    Lesson(
      id: 4,
      level: 'A1',
      title: 'Kundalik Harakatlar',
      vocab: [
        ['Wake up', "Uyg'onmoq"],
        ['Get up', 'Turmoq'],
        ['Drink', 'Ichmoq'],
        ['Eat', 'Yemoq'],
        ['Go to work', 'Ishga bormoq'],
        ['Sleep', 'Uxlamoq'],
        ['Rest', 'Dam olmoq'],
        ['Morning', 'Ertalab'],
        ['Evening', 'Kechqurun'],
        ['Night', 'Kechasi'],
        ['Every day', 'Har kuni'],
        ['Always', 'Doimo'],
        ['Never', "Hech qachon"],
        ['Breakfast', 'Nonushta'],
        ['Lunch', 'Tushlik'],
        ['Dinner', 'Kechki ovqat'],
        ['Coffee', 'Kofe'],
        ['Tea', 'Choy'],
        ['Shower', 'Dush'],
        ['Brush teeth', "Tish cho'tqamoq"],
        ['Read', "O'qimoq"],
        ['Write', 'Yozmoq'],
        ['Study', "O'qish"],
        ['Work', 'Ish'],
        ['Start', 'Boshlamoq'],
      ],
      reading: {
        't': 'Every day, I wake up at 7.\nI drink coffee for breakfast.\nThen I go to work.\nI work from 9 to 5.\nIn the evening, I rest at home.',
        'q': "U ertalab nima ichadi?",
        'o': ['Tea', 'Juice', 'Milk', 'Coffee'],
        'c': 3,
      },
      listening: 'Every day I wake up at seven.',
      writing: "Men har kuni ertalab uyg'onaman.",
      writingSample: 'I wake up at 7 every morning.',
      speaking: 'Describe your morning.',
      grammar: "Uyg'onmoq - Wake up | Ichmoq - To drink",
    ),
    Lesson(
      id: 5,
      level: 'A1',
      title: 'Taom va Ichimlik',
      vocab: [
        ['Water', 'Suv'],
        ['Bread', 'Non'],
        ['Apple', 'Olma'],
        ['Rice', 'Guruch'],
        ['Meat', "Go'sht"],
        ['Milk', 'Sut'],
        ['Eggs', 'Tuxum'],
        ['Fish', 'Baliq'],
        ['Chicken', 'Tovuq'],
        ['Vegetables', 'Sabzavot'],
        ['Fruit', 'Meva'],
        ['Sugar', 'Shakar'],
        ['Salt', 'Tuz'],
        ['I would like', '...istayman'],
        ['Waiter', 'Ofitsiant'],
        ['Delicious', 'Mazzali'],
        ['Hungry', 'Och'],
        ['Thirsty', 'Chanqagan'],
        ['Menu', 'Menyu'],
        ['Order', 'Buyurtma'],
        ['Plate', 'Taroq'],
        ['Fork', 'Sanchq'],
        ['Knife', 'Pichoq'],
        ['Spoon', 'Qoshiq'],
        ['Cup', 'Kupa'],
      ],
      reading: {
        't': 'Waiter: What would you like?\nTom: Rice and chicken, please.\nWaiter: Would you like some water?\nTom: Yes, please. Thank you.',
        'q': 'Tom nima oldi?',
        'o': ['Juice', 'Rice and chicken', 'Coffee', 'Milk'],
        'c': 1,
      },
      listening: 'I would like water and bread, please.',
      writing: 'Men suv va non istayman.',
      writingSample: 'I would like water and bread, please.',
      speaking: 'Order food.',
      grammar: 'I would like - Men istayman | Mazzali - Delicious',
    ),
    Lesson(
      id: 6,
      level: 'A1',
      title: 'Ranglar va Buyumlar',
      vocab: [
        ['Red', 'Qizil'],
        ['Blue', "Ko'k"],
        ['Green', 'Yashil'],
        ['Yellow', 'Sariq'],
        ['White', "O'q"],
        ['Black', 'Qora'],
        ['Orange', "Piyo'z"],
        ['Purple', 'Binafsha'],
        ['Pink', 'Rangli'],
        ['Brown', 'Jigarrang'],
        ['Beautiful', 'Chiroyli'],
        ['Big', 'Katta'],
        ['Small', 'Kichik'],
        ['New', 'Yangi'],
        ['Old', 'Eski'],
        ['Cheap', 'Arzon'],
        ['Expensive', 'Qimmat'],
        ['This is', 'Bu'],
        ['My', 'Mening'],
        ['Shirt', "Ko'ylak"],
        ['Pants', 'Shalvar'],
        ['Shoes', 'Poyabzal'],
        ['Bag', 'Sumka'],
        ['Hat', 'Kepka'],
        ['Dress', 'Kiyim'],
      ],
      reading: {
        't': "Lisa: Look! This is a beautiful red dress.\nAnna: I like green more.\nLisa: What about this blue bag?\nAnna: It's nice but expensive.",
        'q': "Lisa nima yoqtiradi?",
        'o': ['Green bag', 'Red dress', 'Blue shirt', 'Yellow hat'],
        'c': 1,
      },
      listening: 'This is a beautiful blue car.',
      writing: 'Bu chiroyli yashil daftar.',
      writingSample: 'This is a beautiful green notebook.',
      speaking: 'Describe a colorful object.',
      grammar: "Ranglar - Colors | Chiroyli - Beautiful",
    ),
    Lesson(
      id: 7,
      level: 'A1',
      title: 'Vaqt va Kun',
      vocab: [
        ['Monday', 'Dushanba'],
        ['Tuesday', 'Seshanba'],
        ['Wednesday', 'Chorshanba'],
        ['Thursday', 'Payshanba'],
        ['Friday', 'Juma'],
        ['Saturday', 'Shanba'],
        ['Sunday', 'Yakshanba'],
        ['Morning', 'Ertalab'],
        ['Afternoon', 'Kechki'],
        ['Evening', 'Kechqurun'],
        ['Weekend', 'Dam olish'],
        ['Today', 'Bugun'],
        ['Tomorrow', 'Ertaga'],
        ['Yesterday', 'Kecha'],
        ['Now', 'Hozir'],
        ['Time', 'Vaqt'],
        ['Clock', 'Soat'],
        ['Breakfast', 'Nonushta'],
        ['Lunch', 'Tushlik'],
        ['Dinner', 'Kechki'],
        ['Hour', 'Soat'],
        ['Minute', 'Daqiqa'],
        ['Second', 'Soniya'],
        ['Early', 'Erta'],
        ['Late', 'Kech'],
      ],
      reading: {
        't': "It is Monday morning.\nThe time is 8 AM.\nI wake up early.\nI have breakfast at 8:30.\nI go to work at 9.",
        'q': 'Sarah qachon boradi?',
        'o': ['Weekends', 'Monday morning', 'Sunday', 'Night'],
        'c': 1,
      },
      listening: "What time is it? It is eight o'clock.",
      writing: 'Hozir soat 9.',
      writingSample: 'It is 9 AM.',
      speaking: 'Tell the time.',
      grammar: "Kunlar - Days | Vaqt - Time",
    ),
    Lesson(
      id: 8,
      level: 'A1',
      title: 'Sayohat va Joylar',
      vocab: [
        ['Airport', 'Aeroport'],
        ['Hotel', 'Mehmonxona'],
        ['Beach', 'Plyaj'],
        ['Station', 'Stansiya'],
        ['Ticket', 'Chipta'],
        ['Taxi', 'Taksi'],
        ['Bus', 'Avtobus'],
        ['Train', 'Poyezd'],
        ['Where is?', 'Qayerda?'],
        ['Near', 'Yaqinda'],
        ['Far', 'Uzoqda'],
        ['Here', 'Bu yerda'],
        ['There', 'U yerda'],
        ['Left', 'Chap'],
        ['Right', "O'ng"],
        ['Straight', "To'g'ri"],
        ['Turn', 'Burilmoq'],
        ['Excuse me', 'Kechirasiz'],
        ['Map', 'Xarita'],
        ['Passport', 'Pasport'],
        ['Luggage', 'Yuk'],
        ['Room', 'Xona'],
        ['Travel', 'Sayohat'],
        ['Visit', 'Tashrif'],
        ['Holiday', "Ta'til"],
      ],
      reading: {
        't': "Excuse me, where is the hotel?\nIt is near the beach.\nIs it far from here?\nNo, it is not far. Turn left.",
        'q': 'Mehmonxona qayerda?',
        'o': ['Airport', 'Beach', 'Station', 'City'],
        'c': 1,
      },
      listening: 'Where is the hotel?',
      writing: 'Mehmonxona plyaj yaqinida.',
      writingSample: 'The hotel is near the beach.',
      speaking: 'Ask directions.',
      grammar: "Qayerda? - Where? | Yaqinda - Near",
    ),
    Lesson(
      id: 9,
      level: 'A1',
      title: "Do'kon va Xarid",
      vocab: [
        ['Shop', "Do'kon"],
        ['How much?', 'Nechada?'],
        ['Cheap', 'Arzon'],
        ['Expensive', 'Qimmat'],
        ['Money', 'Pul'],
        ['Buy', 'Sotib olmoq'],
        ['Price', 'Narx'],
        ['Discount', 'Chegirma'],
        ['Cash', 'Naqd'],
        ['Card', 'Karta'],
        ['Size', "O'lcham"],
        ['Color', 'Rang'],
        ['Shirt', "Ko'ylak"],
        ['Phone', 'Telefon'],
        ['Bag', 'Sumka'],
        ['Sale', 'Chegirma'],
        ['Receipt', 'Check'],
        ['Want', 'Xohlamoq'],
        ['Need', 'Kerak'],
        ['Show', "Ko'rsatmoq"],
        ['Try', 'Sinamoq'],
        ['Change', 'Almashtirmoq'],
        ['Return', 'Qaytarmoq'],
        ['Cheap', 'Arzon'],
        ['Expensive', 'Qimmat'],
      ],
      reading: {
        't': "How much is this shirt?\nIt is 50,000 so'm.\nThat's expensive.\nDo you have a smaller size?\nYes, here you go.",
        'q': "Ko'ylak qancha turadi?",
        'o': ['30,000', '50,000', '20,000', '100,000'],
        'c': 1,
      },
      listening: 'How much is this book?',
      writing: 'Bu kitob qancha turadi?',
      writingSample: 'How much is this book?',
      speaking: 'Ask about prices.',
      grammar: "Nechada? - How much? | Narx - Price",
    ),
    Lesson(
      id: 10,
      level: 'A1',
      title: "Ob-havo va Fasllar",
      vocab: [
        ['Hot', 'Issiq'],
        ['Cold', 'Sovuq'],
        ['Rain', "Yomg'ir"],
        ['Snow', 'Qor'],
        ['Wind', 'Shamol'],
        ['Sun', 'Quyosh'],
        ['Cloud', 'Bulut'],
        ['Summer', 'Yoz'],
        ['Winter', 'Qish'],
        ['Spring', 'Bahor'],
        ['Autumn', 'Kuz'],
        ['Warm', 'Iliq'],
        ['Cool', 'Salqin'],
        ['Umbrella', 'Soyanchqa'],
        ['Jacket', 'Kurtka'],
        ['Sunny', 'Quyoshli'],
        ['Cloudy', 'Bulutli'],
        ['Windy', 'Shamolli'],
        ['Weather', 'Ob-havo'],
        ['Temperature', 'Harorat'],
        ['Today', 'Bugun'],
        ['Tomorrow', 'Ertaga'],
        ['Nice', 'Chiroyli'],
        ['Ice', 'Muz'],
        ['Frost', 'Muzlash'],
      ],
      reading: {
        't': "Today is very hot.\nThe sun is shining.\nIt is summer now.\nI like summer because I can swim.\nBut I don't like the heat.",
        'q': 'Bugun qanday?',
        'o': ['Sovuq', 'Issiq', "Yomg'ir", 'Bulutli'],
        'c': 1,
      },
      listening: 'It is raining today.',
      writing: 'Bugun juda issiq.',
      writingSample: 'Today is very hot.',
      speaking: 'Describe weather.',
      grammar: "Issiq - Hot | Sovuq - Cold | Yomg'ir - Rain",
    ),
    Lesson(
      id: 11,
      level: 'A1',
      title: 'Kasblar va Ish',
      vocab: [
        ['Doctor', 'Shifokor'],
        ["Teacher", "O'qituvchi"],
        ['Engineer', 'Muhandis'],
        ['Nurse', 'Hamshira'],
        ['Driver', 'Haydovchi'],
        ['Cook', 'Oshpaz'],
        ['Farmer', 'Dehqon'],
        ['Worker', 'Ishchi'],
        ['Boss', 'Rahbar'],
        ['Hospital', 'Kasalxona'],
        ['School', 'Maktab'],
        ['Office', 'Idora'],
        ['Work', 'Ish'],
        ['Job', 'Kasb'],
        ['I work at', 'Men ishlayman'],
        ['I am a', 'Men ...man'],
        ['Want to be', "Bo'lmoqchi"],
        ['Bank', 'Bank'],
        ['Factory', 'Zavod'],
        ['Money', 'Pul'],
        ['Team', 'Jamoah'],
        ['Help', 'Yordam'],
        ['Good', 'Yaxshi'],
        ['Busy', 'Band'],
        ['Free', 'Bo\'sh'],
      ],
      reading: {
        't': "Ali is a doctor.\nHe works at a hospital.\nHe helps sick people.\nHe works from Monday to Friday.\nHe likes his job.",
        'q': "Ali nima qiladi?",
        'o': ['Driver', 'Teacher', 'Doctor', 'Cook'],
        'c': 2,
      },
      listening: 'I am a doctor at the hospital.',
      writing: 'Men o\'qituvchiman.',
      writingSample: 'I am a teacher.',
      speaking: 'Talk about your job.',
      grammar: "Kasb - Job | Ish - Work | Rahbar - Boss",
    ),
    Lesson(
      id: 12,
      level: 'A1',
      title: 'Hobbi va Qiziqishlar',
      vocab: [
        ['Hobby', 'Hobbi'],
        ['Football', 'Futbol'],
        ['Basketball', 'Basketbol'],
        ['Swimming', 'Suzish'],
        ['Running', 'Yugurish'],
        ['Reading', "O'qish"],
        ['Singing', 'Kuflash'],
        ['Dancing', 'Raqs'],
        ['Cooking', 'Pishirish'],
        ['Painting', 'Rasm chizish'],
        ['Music', 'Musiqa'],
        ['Film', 'Film'],
        ['Game', 'O\'yin'],
        ['Guitar', 'Gitarra'],
        ['Piano', 'Piano'],
        ['Enjoy', 'Zavq olmoq'],
        ['Like', 'Yoqtirmoq'],
        ['Love', 'Sevmok'],
        ['Play', 'O\'ynamoq'],
        ['Watch', 'Ko\'rmoq'],
        ['Listen', 'Eslatmoq'],
        ['Practice', 'Mashq qilmoq'],
        ['Fun', 'Ko\'ngiloch'],
        ['Interesting', 'Qiziqarli'],
        ['Boring', 'zerikarli'],
      ],
      reading: {
        't': "My hobby is reading books.\nI read every day before sleep.\nI also like swimming.\nI go to the pool on Saturdays.\nWhat about you?",
        'q': 'Nima o\'qish yoqadi?',
        'o': ['Football', 'Reading', 'Cooking', 'Dancing'],
        'c': 1,
      },
      listening: 'I like reading and swimming.',
      writing: 'Mening hobbiim o\'qish.',
      writingSample: 'My hobby is reading.',
      speaking: 'Talk about your hobbies.',
      grammar: "Hobbi - Hobby | Yoqtirmoq - To like",
    ),
    Lesson(
      id: 13,
      level: 'A1',
      title: "Do'stlar va Ijtimoiy",
      vocab: [
        ["Friend", "Do'st"],
        ['Best friend', "Eng yaqin do'st"],
        ['Party', 'Ziyofat'],
        ['Birthday', "Tug'ilgan kun"],
        ['Gift', 'Sovga'],
        ['Cake', 'Tort'],
        ['Fun', 'Ko\'ngiloch'],
        ['Laugh', 'Kulmoq'],
        ['Smile', 'Tabassum qilmoq'],
        ['Cry', 'Yig\'lamoq'],
        ['Happy', 'Baxtli'],
        ['Sad', 'G\'amgin'],
        ['Angry', 'G\'azablangan'],
        ['Kind', 'Mehrmondo\'st'],
        ['Mean', 'Yomon'],
        ['Together', 'Birga'],
        ['Share', 'Ulashmoq'],
        ['Help', 'Yordam'],
        ['Trust', 'Ishonmoq'],
        ['Invite', 'Taklif qilmoq'],
        ['Celebrate', 'Nishonlamoq'],
        ['Remember', 'Eslamoq'],
        ['Forget', 'Unutmoq'],
        ['Hug', 'Quchoqlamoq'],
        ['Wave', 'Lik qilmoq'],
      ],
      reading: {
        't': "Ali is my best friend.\nWe play football together.\nYesterday was his birthday.\nI gave him a gift.\nWe had a great party!",
        'q': "Ali kimga sovga berdi?",
        'o': ['Teacher', 'Mother', 'Ali', 'Father'],
        'c': 2,
      },
      listening: "Ali is my best friend.",
      writing: "Ali mening eng yaqin do'stim.",
      writingSample: 'Ali is my best friend.',
      speaking: 'Describe your friend.',
      grammar: "Do'st - Friend | Ziyofat - Party",
    ),
    Lesson(
      id: 14,
      level: 'A1',
      title: "Sog'liq va Tibbiyot",
      vocab: [
        ['Sick', 'Kasal'],
        ['Healthy', 'Sog\'lom'],
        ['Pain', "Og'riq"],
        ['Headache', "Bosh og'rig'i"],
        ['Fever', 'Isitma'],
        ['Cough', 'Yo\'tal'],
        ['Cold', 'Grip'],
        ['Medicine', 'Dori'],
        ['Pharmacy', 'Dorixona'],
        ['Hospital', 'Kasalxona'],
        ['Doctor', 'Shifokor'],
        ['Nurse', 'Hamshira'],
        ['Feel', 'His qilmoq'],
        ['Better', 'Yaxshiroq'],
        ['Worse', 'Yomonroq'],
        ['Rest', 'Dam olmoq'],
        ['Sleep', 'Uxlamoq'],
        ['Drink water', 'Suv ichmoq'],
        ['Exercise', 'Mashq qilmoq'],
        ['Diet', 'Parhez'],
        ['Allergy', 'Allergiya'],
        ['Bandage', 'Bandaj'],
        ['Temperature', 'Harorat'],
        ['Blood', 'Qon'],
        ['Stomach', 'Oshqozon'],
      ],
      reading: {
        't': "I don't feel well today.\nI have a headache and fever.\nI went to the doctor.\nThe doctor gave me medicine.\nI need to rest at home.",
        'q': "Kasalning bosh og'rig'i bor?",
        'o': ['Doctor', 'Ali', 'Patient', 'Nurse'],
        'c': 2,
      },
      listening: "I don't feel well today.",
      writing: "Bugun o'zimni yomon his qilyapman.",
      writingSample: "I don't feel well today.",
      speaking: 'Describe how you feel.',
      grammar: "Sog'lom - Healthy | Kasal - Sick",
    ),
    // A2 Level
    Lesson(
      id: 15,
      level: 'A2',
      title: 'Past Simple',
      vocab: [
        ['Yesterday', 'Kecha'],
        ['Last week', 'O\'tgan hafta'],
        ['Last month', 'O\'tgan oy'],
        ['Last year', 'O\'tgan yil'],
        ['Went', 'Bordi'],
        ['Came', 'Keldi'],
        ['Ate', 'Yedi'],
        ['Drank', 'Ichdi'],
        ['Saw', 'Ko\'rdi'],
        ['Heard', 'Esladi'],
        ['Played', "O'ynadi"],
        ['Watched', 'Ko\'rdi'],
        ['Listened', 'Esladi'],
        ['Read', "O'qidi"],
        ['Wrote', 'Yozdi'],
        ['Talked', 'Gaplashdi'],
        ['Worked', 'Ishladi'],
        ['Studied', "O'qidi"],
        ['Cooked', "Pishirdi"],
        ['Walked', 'Yurdi'],
        ['Ran', 'Yugurdi'],
        ['Slept', 'Uxladi'],
        ['Lived', 'Yashadi'],
        ['Moved', 'Ko\'chdi'],
        ['Finished', 'Tugatdi'],
      ],
      reading: {
        't': "Yesterday, I went to the market.\nI bought some fruit and vegetables.\nI also met my friend Ali.\nWe talked for an hour.\nThen I came home.",
        'q': "U o'tgan kuni qayerga bordi?",
        'o': ['School', 'Market', 'Hospital', 'Park'],
        'c': 1,
      },
      listening: "Yesterday I went to the market.",
      writing: "Men o'tgan hafta do'konga bordim.",
      writingSample: "I went to the shop last week.",
      speaking: "Talk about yesterday.",
      grammar: "O'tgan zamon - Past Simple | WENT - GO past",
    ),
    Lesson(
      id: 16,
      level: 'A2',
      title: 'Kelajak (Future)',
      vocab: [
        ['Tomorrow', 'Ertaga'],
        ['Next week', 'Keyingi hafta'],
        ['Next month', 'Keyingi oy'],
        ['Next year', 'Keyingi yil'],
        ['Will', '—'],
        ["Going to", '—'],
        ['Plan', 'Reja'],
        ['Want', 'Istamoq'],
        ['Hope', 'Umid qilmoq'],
        ['Think', 'O\'ylamoq'],
        ['Maybe', 'Ehtimol'],
        ['Probably', 'Ehtimol'],
        ['Definitely', 'Albatta'],
        ['Soon', 'Tez orada'],
        ['Later', 'Keyin'],
        ['Travel', 'Sayohat'],
        ['Study', "O'qish"],
        ['Work', 'Ishlamoq'],
        ['Move', "Ko'chmoq"],
        ['Start', 'Boshlamoq'],
        ['Finish', 'Tugatmoq'],
        ['Buy', 'Sotib olmoq'],
        ['Sell', 'Sotmoq'],
        ['Learn', "O'rganmoq"],
        ['Practice', 'Mashq qilmoq'],
      ],
      reading: {
        't': "I am going to travel next month.\nI will visit London.\nI want to see Big Ben.\nI think I will have a great time.\nMaybe I will learn English there.",
        'q': "U keyingi oy nima qiladi?",
        'o': ['Study', 'Travel', 'Work', 'Move'],
        'c': 1,
      },
      listening: "I am going to travel next month.",
      writing: "Men keyingi oy sayohat qilaman.",
      writingSample: "I will travel next month.",
      speaking: "Talk about your future plans.",
      grammar: "Kelajak - Future | Will / Going to",
    ),
    Lesson(
      id: 17,
      level: 'A2',
      title: 'Taqqoslash',
      vocab: [
        ['Bigger', 'Kattaroq'],
        ['Smaller', 'Kichikroq'],
        ['Better', 'Yaxshiroq'],
        ['Worse', 'Yomonroq'],
        ['Faster', 'Tezroq'],
        ['Slower', 'Sekinroq'],
        ['More', "Ko'proq"],
        ['Less', 'Kamroq'],
        ['Than', '...dan'],
        ['The most', 'Eng ...'],
        ['The least', 'Eng kam'],
        ['Taller', 'Bo'yinga balandroq'],
        ['Shorter', 'Qisqaroq'],
        ['Older', 'Kattaroq'],
        ['Younger', 'Yoshroq'],
        ['Cheaper', 'Arzonroq'],
        ['More expensive', 'Qimmatroq'],
        ['Easier', 'Osonroq'],
        ['Harder', 'Qiyinroq'],
        ['Interesting', 'Qiziqarli'],
        ['Beautiful', 'Chiroyli'],
        ['Fast', 'Tez'],
        ['Slow', 'Sekin'],
        ['Good', 'Yaxshi'],
        ['Bad', 'Yomon'],
      ],
      reading: {
        't': "Tashkent is bigger than Samarkand.\nBut Samarkand is more beautiful.\nThe weather in winter is colder than in summer.\nI think football is more interesting than basketball.\nWhich do you prefer?",
        'q': "Qaysi shahar kattaroq?",
        'o': ['Samarkand', 'Tashkent', 'Bukhara', 'Khiva'],
        'c': 1,
      },
      listening: "Tashkent is bigger than Samarkand.",
      writing: "Toshkent Samarkanddan kattaroq.",
      writingSample: "Tashkent is bigger than Samarkand.",
      speaking: "Compare two things.",
      grammar: "Taqqoslash - Comparatives | MORE / -ER",
    ),
    Lesson(
      id: 18,
      level: 'A2',
      title: 'So\'rov va Iltimos',
      vocab: [
        ['Can you?', 'Siz ... olasizmi?'],
        ['Could you?', 'Siz ... olardingizmi?'],
        ['Would you like?', 'Siz xohlaysizmi?'],
        ['May I?', 'Men ... mumkinmi?'],
        ['Please', 'Iltimos'],
        ['Thank you', 'Rahmat'],
        ['You\'re welcome', 'Arzimaydi'],
        ['Sorry', 'Kechirasiz'],
        ['Excuse me', 'Kechirasiz'],
        ['Help', 'Yordam'],
        ['Borrow', 'O\'zlatib olish'],
        ['Lend', 'Bermoq'],
        ['Give', 'Bermoq'],
        ['Take', 'Olish'],
        ['Bring', 'Keltirmoq'],
        ['Show', "Ko'rsatmoq"],
        ['Tell', 'Aytmoq'],
        ['Explain', 'Tushuntirmoq'],
        ['Wait', 'Kutilmoq'],
        ['Hurry', 'Tezlashmoq'],
        ['Start', 'Boshlamoq'],
        ['Stop', 'To\'xtatmoq'],
        ['Open', 'Ochmoq'],
        ['Close', 'Yopmoq'],
        ['Turn on', 'Yondirmoq'],
      ],
      reading: {
        't': "Excuse me, could you help me?\nI need to find the train station.\nSure! Go straight and turn left.\nThank you very much.\nYou're welcome!",
        'q': "Qaysi joy kerak?",
        'o': ['Hotel', 'Train station', 'Airport', 'Hospital'],
        'c': 1,
      },
      listening: "Could you help me, please?",
      writing: "Men poezd stansiyasini topishim kerak.",
      writingSample: "I need to find the train station.",
      speaking: "Ask for help politely.",
      grammar: "Iltimos - Please | Could you? - Would you?",
    ),
    Lesson(
      id: 19,
      level: 'A2',
      title: 'Sarflar va Byudjet',
      vocab: [
        ['Salary', 'Oylik'],
        ['Save', 'Saqlamoq'],
        ['Spend', 'Sarflamoq'],
        ['Cost', 'Narxi'],
        ['Price', 'Narx'],
        ['Cheap', 'Arzon'],
        ['Expensive', 'Qimmat'],
        ['Budget', 'Byudjet'],
        ['Bill', 'Hisob'],
        ['Tax', 'Soliq'],
        ['Rent', 'Ijara'],
        ['Electricity', 'Elektr'],
        ['Water', 'Suv'],
        ['Food', 'Ovqat'],
        ['Transport', 'Transport'],
        ['Clothes', 'Kiyim'],
        ['Cheap', 'Arzon'],
        ['Free', 'Bepul'],
        ['Cash', 'Naqd'],
        ['Card', 'Karta'],
        ['Bank', 'Bank'],
        ['Account', 'Hisob'],
        ['Debt', 'Qarz'],
        ['Invest', 'Sarmoya'],
        ['Profit', 'Foyda'],
      ],
      reading: {
        't': "My salary is 5 million so'm.\nI spend 2 million on rent.\nI spend 1 million on food.\nI save 2 million every month.\nI want to buy a new phone.",
        'q': "U necha pul saqlaydi?",
        'o': ['1 million', '2 million', '3 million', '5 million'],
        'c': 1,
      },
      listening: "I save 2 million every month.",
      writing: "Men har oy 2 million so'm saqlayman.",
      writingSample: "I save 2 million every month.",
      speaking: "Talk about your budget.",
      grammar: "Sarflamoq - To spend | Saqlamoq - To save",
    ),
    Lesson(
      id: 20,
      level: 'A2',
      title: "Sog'liq va Sport",
      vocab: [
        ['Exercise', 'Mashq'],
        ['Gym', 'Sport zal'],
        ['Weight', 'Og\'irligi'],
        ['Diet', 'Parhez'],
        ['Calories', 'Kaloriya'],
        ['Protein', 'Oqsil'],
        ['Breakfast', 'Nonushta'],
        ['Lunch', 'Tushlik'],
        ['Dinner', 'Kechki ovqat'],
        ['Healthy', 'Sog\'lom'],
        ['Junk food', 'Fast food'],
        ['Fruit', 'Meva'],
        ['Vegetable', 'Sabzavot'],
        ['Walk', 'Yurish'],
        ['Run', 'Yugurish'],
        ['Swim', 'Suzish'],
        ['Sleep', 'Uxlash'],
        ['Water', 'Suv'],
        ['Doctor', 'Shifokor'],
        ['Hospital', 'Kasalxona'],
        ['Medicine', 'Dori'],
        ['Pain', 'Og\'riq'],
        ['Rest', 'Dam olish'],
        ['Stress', 'Stress'],
        ['Energy', 'Energiya'],
      ],
      reading: {
        't': "I go to the gym three times a week.\nI do exercise for one hour.\nI eat healthy food.\nI don't eat junk food.\nI drink a lot of water.",
        'q': "U necha marta sport zalga boradi?",
        'o': ['Once', 'Twice', 'Three times', 'Four times'],
        'c': 2,
      },
      listening: "I go to the gym three times a week.",
      writing: "Men haftasiga uch marta sport zalga boraman.",
      writingSample: "I go to the gym three times a week.",
      speaking: "Talk about your exercise routine.",
      grammar: "Sport - Exercise | Sog'lom - Healthy",
    ),
    Lesson(
      id: 21,
      level: 'A2',
      title: 'Texnologiya va Internet',
      vocab: [
        ['Computer', 'Kompyuter'],
        ['Phone', 'Telefon'],
        ['Internet', 'Internet'],
        ['Website', 'Sayt'],
        ['App', 'Ilova'],
        ['Download', 'Yuklab olish'],
        ['Upload', "Yuklash"],
        ['Email', 'Xat'],
        ['Password', 'Parol'],
        ['Search', 'Qidirmoq'],
        ['Click', 'Bosmoq'],
        ['Type', 'Yozmoq'],
        ['Screen', 'Ekran'],
        ['Keyboard', 'Klaviatura'],
        ['Mouse', 'Sichqoncha'],
        ['Bluetooth', 'Bluetooth'],
        ['WiFi', 'WiFi'],
        ['Battery', 'Batareya'],
        ['Charge', 'Zaryad'],
        ['Message', 'Xabar'],
        ['Video', 'Video'],
        ['Photo', 'Rasm'],
        ['Social media', 'Ijtimoiy tarmoq'],
        ['Online', 'Onlayn'],
        ['Offline', 'Oflayn'],
      ],
      reading: {
        't': "I use my computer every day.\nI search for information online.\nI send emails to my friends.\nI also use social media.\nBut I try not to spend too much time.",
        'q': "U internetdan nima uchun foydalanadi?",
        'o': ['Gaming', 'Search info', 'Shopping', 'Travel'],
        'c': 1,
      },
      listening: "I use my computer every day.",
      writing: "Men har kuni kompyuterdan foydalanaman.",
      writingSample: "I use my computer every day.",
      speaking: "Talk about technology.",
      grammar: "Kompyuter - Computer | Internet - Internet",
    ),
    // B1 Level
    Lesson(
      id: 22,
      level: 'B1',
      title: 'Past Perfect',
      vocab: [
        ['Had', '...gan edi'],
        ['Before', 'Oldin'],
        ['After', 'Keyin'],
        ['Already', 'Allaqachon'],
        ['Yet', 'Hali'],
        ['Just', 'Endigina'],
        ['Never', 'Hech qachon'],
        ['Ever', 'Hech qachon'],
        ['Since', '...dan beri'],
        ['For', '... davomida'],
        ['Arrived', 'Kelgan'],
        ['Left', 'Ketgan'],
        ['Finished', 'Tugatgan'],
        ['Started', 'Boshlagan'],
        ['Waited', 'Kutilgan'],
        ['Learned', "O'rgangan"],
        ['Thought', "O'ylagan"],
        ['Said', 'Aytgan'],
        ['Gone', 'Borgan'],
        ['Come', 'Kelgan'],
        ['Been', 'Bo'lgan'],
        ['Done', 'Qilgan'],
        ['Seen', 'Ko'rgan'],
        ['Heard', 'Eslagan'],
        ['Read', "O'qigan"],
      ],
      reading: {
        't': "When I arrived, they had already left.\nI had never been to London before.\nShe had finished her homework before I came.\nWe had lived there for five years.\nBy the time he called, I had gone to bed.",
        'q': "Men kelganda nima bo'lgan?",
        'o': ['They arrived', 'They left', 'I left', 'They slept'],
        'c': 1,
      },
      listening: "When I arrived, they had already left.",
      writing: "Men kelganda ular allaqachon ketishgan edi.",
      writingSample: "When I arrived, they had already left.",
      speaking: "Talk about a past experience.",
      grammar: "Past Perfect - HAD + V3 | Oldingi voqea",
    ),
    Lesson(
      id: 23,
      level: 'B1',
      title: 'Passive Voice',
      vocab: [
        ['Was/Were', '... edi'],
        ['Is/Are', '...dir'],
        ['Been', '...gan'],
        ['By', '... tomonidan'],
        ['Made', 'Yasalgan'],
        ['Built', 'Qurilgan'],
        ['Written', 'Yozilgan'],
        ['Spoken', 'Aytilgan'],
        ['Read', "O'qilgan"],
        ['Seen', "Ko'rilgan"],
        ['Heard', 'Eshitilgan'],
        ['Known', "Bilgan"],
        ['Taken', 'Olingan'],
        ['Given', 'Berilgan'],
        ['Sold', 'Sotilgan'],
        ['Bought', 'Sotib olingan'],
        ['Opened', 'Ochilgan'],
        ['Closed', 'Yopilgan'],
        ['Used', 'Ishlatilgan'],
        ['Broken', 'Sinib ketgan'],
        ['Lost', "Yo'qolgan"],
        ['Found', 'Topilgan'],
        ['Sent', 'Yuborilgan'],
        ['Received', 'Qabul qilingan'],
        ['Cleaned', 'Tozalangan'],
      ],
      reading: {
        't': "The building was built in 1990.\nEnglish is spoken in many countries.\nThe book was written by a famous author.\nCars are made in factories.\nThe homework has been finished.",
        'q': "Ingliz tili qayerda gaplashiladi?",
        'o': ['One country', 'Many countries', 'Only UK', 'Only US'],
        'c': 1,
      },
      listening: "English is spoken in many countries.",
      writing: "Ingliz tili ko'p mamlakatlarda gaplashiladi.",
      writingSample: "English is spoken in many countries.",
      speaking: "Describe how things are made.",
      grammar: "Passive Voice - Fe'l laykalishi | IS/ARE/WAS/WERE + V3",
    ),
    Lesson(
      id: 24,
      level: 'B1',
      title: 'Reported Speech',
      vocab: [
        ['Said', 'Dedi'],
        ['Told', 'Aytadi'],
        ['Asked', 'So\'radi'],
        ['Explained', 'Tushuntirdi'],
        ['That', '...ligini'],
        ['If', 'Agar'],
        ['Whether', '...ligini'],
        ['Could', '... ola'],
        ['Would', '... qilardi'],
        ['Should', '... kerak'],
        ['Might', '... mumkin'],
        ['Can', '... oladi'],
        ['Will', '... qiladi'],
        ['Do', '... qiladi'],
        ['Does', '... qiladi'],
        ['Did', '... qildi'],
        ['Was', '... edi'],
        ['Were', '... edi'],
        ['Had', '... edi'],
        ['Have', '... bor'],
        ['Has', '... bor'],
        ['Go', '... bormoq'],
        ['Come', '... kelmoq'],
        ['Want', '... xohlaydi'],
        ['Need', '... kerak'],
      ],
      reading: {
        't': "Ali said: 'I am tired.'\nAli said that he was tired.\nShe said: 'I will come tomorrow.'\nShe said that she would come the next day.\nHe asked: 'Do you speak English?'",
        'q': "Ali nima dedi?",
        'o': ['He is tired', 'He is happy', 'He is hungry', 'He is busy'],
        'c': 0,
      },
      listening: "Ali said that he was tired.",
      writing: "Ali charchaganini aytdi.",
      writingSample: "Ali said that he was tired.",
      speaking: "Report what someone said.",
      grammar: "Reported Speech - Bilim berish | SAID THAT ...",
    ),
    Lesson(
      id: 25,
      level: 'B1',
      title: 'Conditionals',
      vocab: [
        ['If', 'Agar'],
        ['Unless', 'Agar ...masa'],
        ['Provided that', 'Agar ...lsa'],
        ['In case', 'Agar ...lsa'],
        ['Were', '... edi'],
        ['Would', '... qilardi'],
        ['Could', '... ola'],
        ['Might', '... mumkin'],
        ['Should', '... kerak'],
        ['Probably', 'Ehtimol'],
        ['Maybe', 'Ehtimol'],
        ['Definitely', 'Albatta'],
        ['Certainly', 'Albatta'],
        ['Imagine', 'Tasavvur qiling'],
        ['Suppose', 'Hisob qiling'],
        ['Assume', 'Taxmin qiling'],
        ['If I were', 'Agar men ... bo\'lsam'],
        ['I would', 'Men ... qilardim'],
        ['I could', 'Men ... qila olardim'],
        ['I might', 'Men ... mumkin'],
        ['Rain', "Yomg'ir"],
        ['Travel', 'Sayohat qilmoq'],
        ['Win', 'Yutmoq'],
        ['Lose', "Yo'qotmoq"],
        ['Winning', 'Yutish'],
      ],
      reading: {
        't': "If it rains tomorrow, I will stay home.\nIf I had money, I would travel the world.\nIf you study hard, you will pass the exam.\nUnless you hurry, you will be late.\nIf I were you, I would learn English.",
        'q': "Agar ertaga yomg'ir yog'sa nima qiladi?",
        'o': ['Travel', 'Stay home', 'Go to work', 'Study'],
        'c': 1,
      },
      listening: "If it rains, I will stay home.",
      writing: "Agar yomg'ir yog'sa, men uyda qolaman.",
      writingSample: "If it rains, I will stay home.",
      speaking: "Talk about hypothetical situations.",
      grammar: "Zero/First/Second/Third Conditionals",
    ),
    Lesson(
      id: 26,
      level: 'B1',
      title: 'Phrasal Verbs',
      vocab: [
        ['Look after', 'G\'amxo\'rlik qilmoq'],
        ['Look for', 'Qidirmoq'],
        ['Look up', "Ma'lumot qidirmoq"],
        ['Give up', "Taslim bo'lmoq"],
        ['Give in', "Yengilmaslik"],
        ['Turn on', 'Yondirmoq'],
        ['Turn off', "O'chirmoq"],
        ['Turn up', "Ko'tarmoq"],
        ['Turn down', "Pasaytirmoq"],
        ['Put on', 'Kiyish'],
        ['Take off', 'Chiqarmoq'],
        ['Get up', 'Turmoq'],
        ['Go on', 'Davom etmoq'],
        ['Come back', 'Qaytmoq'],
        ['Run out', 'Tugamoq'],
        ['Pick up', 'Olmoq'],
        ['Set up', 'O\'rnatmoq'],
        ['Bring up', 'Tarbiyalamoq'],
        ['Find out', 'Topmoq'],
        ['Figure out', 'Tushunmoq'],
        ['Hang out', 'O\'ynamoq'],
        ['Break down', 'Buzilmoq'],
        ['Run into', 'Uchrashmoq'],
        ['Get along', "Yaxshi munosabatda"],
        ['Put up with', "Chidamoq"],
      ],
      reading: {
        't': "I need to look up this word.\nDon't give up! You can do it.\nShe turned down the offer.\nWe need to figure out the problem.\nI ran into my old friend yesterday.",
        'q': "U qadimgi do'stini qayerda uchratdi?",
        'o': ['Home', 'School', 'Randomly', 'Market'],
        'c': 2,
      },
      listening: "I ran into my old friend.",
      writing: "Men qadimgi do'stimni uchratdim.",
      writingSample: "I ran into my old friend yesterday.",
      speaking: "Use phrasal verbs in sentences.",
      grammar: "Phrasal Verbs - Fe'l + predlog | 30+ ta mashhur",
    ),
    Lesson(
      id: 27,
      level: 'B1',
      title: 'Idioms',
      vocab: [
        ['Break a leg', 'Omading bo\'lsin'],
        ['Hit the nail', "To'g'ri aytish"],
        ['Piece of cake', "Oson ish"],
        ['Cost an arm', 'Juda qimmat'],
        ['Under the weather', 'Kasal'],
        ['Kill two birds', 'Ikkita tong\'a'],
        ['Bite the bullet', 'Jasorat qilmoq'],
        ['Let the cat out', 'Sirni ochmoq'],
        ['Once in a blue moon', "Juda kam"],
        ['Hit the books', "O'qish"],
        ['Break the ice', 'Muzni sindirmoq'],
        ['Cost an arm', 'Qimmat'],
        ['Burning the midnight oil', 'Kechasi ishlamoq'],
        ['Actions speak louder', 'Amal so\'zdan balandroq'],
        ['The ball is in your court', 'Navbat senda'],
        ['Beat around the bush', "To'g'ri gapirmaslik"],
        ['Bite off more than', "Ko'p olmoq"],
        ['Blessing in disguise', 'Yomonlikda yaxshilik'],
        ['Call it a day', 'Tugatmoq'],
        ['Cut corners', 'Tejamkorlik'],
        ['Easy as pie', "Oson"],
        ['Get out of hand', 'Nazoratdan chiqmoq'],
        ['Go the extra mile', "Ko'p harakat"],
        ['Hang in there', 'Chidang'],
        ['Keep an eye on', 'Kuzatmoq'],
      ],
      reading: {
        't': "The exam was a piece of cake.\nI was under the weather last week.\nDon't beat around the bush.\nJust hit the books and you'll pass.\nActions speak louder than words.",
        'q': "Imtihon qanday o'tdi?",
        'o': ['Qiyin', 'Oson', 'O\'rta', 'Juda qiyin'],
        'c': 1,
      },
      listening: "The exam was a piece of cake.",
      writing: "Imtihon juda oson o'tdi.",
      writingSample: "The exam was a piece of cake.",
      speaking: "Use idioms in conversation.",
      grammar: "Idioms - Maqollar | 20+ ta eng mashhur",
    ),
    Lesson(
      id: 28,
      level: 'B1',
      title: 'Ish hayoti',
      vocab: [
        ['Interview', 'Suhbat'],
        ['Resume', 'Rezyume'],
        ['Salary', 'Oylik'],
        ['Promotion', 'Lavozim oshirish'],
        ['Deadline', 'Muddat'],
        ['Meeting', 'Yig\'ilish'],
        ['Project', 'Loyiha'],
        ['Team', 'Jamoah'],
        ['Boss', 'Rahbar'],
        ['Colleague', 'Hamkasb'],
        ['Office', 'Idora'],
        ['Schedule', 'Jadval'],
        ['Task', 'Vazifa'],
        ['Goal', 'Maqsad'],
        ['Achievement', 'Yutuq'],
        ['Experience', 'Tajriba'],
        ['Skill', 'Ko\'nikma'],
        ['Qualification', 'Malaka'],
        ['Application', 'Ariza'],
        ['Hired', 'Ishga qabul qilindi'],
        ['Fired', 'Ishdan bo\'shatildi'],
        ['Resigned', 'Istefa'],
        ['Retired', 'Nafaqaga chiqdi'],
        ['Contract', 'Shartnoma'],
        ['Benefit', 'Imtiyoz'],
      ],
      reading: {
        't': "I have a job interview tomorrow.\nI need to prepare my resume.\nI have five years of experience.\nI am good at working in a team.\nI hope I get the job.",
        'q': "Uning ertaga nima rejalari bor?",
        'o': ['Meeting', 'Interview', 'Deadline', 'Holiday'],
        'c': 1,
      },
      listening: "I have a job interview tomorrow.",
      writing: "Men ertaga ish suhbatiga boraman.",
      writingSample: "I have a job interview tomorrow.",
      speaking: "Talk about work experience.",
      grammar: "Ish - Work | Suhbat - Interview",
    ),
    Lesson(
      id: 29,
      level: 'B1',
      title: 'Sayohat (Advanced)',
      vocab: [
        ['Passport', 'Pasport'],
        ['Visa', 'Viza'],
        ['Customs', 'Bojxona'],
        ['Luggage', 'Yuk'],
        ['Reservation', 'Bron'],
        ['Cancellation', 'Bekor qilish'],
        ['Itinerary', 'Yo\'nalish'],
        ['Destination', 'Manzil'],
        ['Departure', 'Jo\'nash'],
        ['Arrival', 'Yetib kelish'],
        ['Layover', 'To\'xtash'],
        ['Terminal', 'Terminal'],
        ['Boarding pass', 'Bort kartochkasi'],
        ['Car rental', 'Mashina ijarasi'],
        ['Tour guide', 'Sayohat yo\'riqchisi'],
        ['Souvenir', 'Sovg\'a'],
        ['Scenic', 'Go\'zal manzara'],
        ['Adventure', 'Sarguzasht'],
        ['Exploration', 'Tadqiqot'],
        ['Culture', 'Madaniyat'],
        ['Tradition', 'An\'ana'],
        ['Local', 'Mahalliy'],
        ['Foreign', 'Chet el'],
        ['Abroad', 'Chet elda'],
        ['Tourist', 'Sayyoh'],
      ],
      reading: {
        't': "Last summer, I traveled to Turkey.\nI went by plane from Tashkent.\nThe flight was six hours.\nI visited Istanbul and Antalya.\nThe food was delicious and people were friendly.",
        'q': "U qayerga sayohat qildi?",
        'o': ['Russia', 'Turkey', 'China', 'Iran'],
        'c': 1,
      },
      listening: "I traveled to Turkey last summer.",
      writing: "Men o'tgan yozda Turkiyaga sayohat qildim.",
      writingSample: "I traveled to Turkey last summer.",
      speaking: "Describe a travel experience.",
      grammar: "Sayohat - Travel | Pasport - Passport",
    ),
    Lesson(
      id: 30,
      level: 'B1',
      title: 'Madaniyat va Jamiyat',
      vocab: [
        ['Culture', 'Madaniyat'],
        ['Tradition', 'An\'ana'],
        ['Custom', "Odat"],
        ['Society', 'Jamiyat'],
        ['Community', 'Jamoat'],
        ['Religion', 'Din'],
        ['Celebration', 'Bayram'],
        ['Festival', 'Festival'],
        ['Ceremony', 'Marosim'],
        ['Respect', 'Hurmat'],
        ['Value', 'Qiymat'],
        ['Belief', 'E\'tiqod'],
        ['Heritage', 'Meros'],
        ['Art', 'San\'at'],
        ['Music', 'Musiqa'],
        ['Dance', 'Raqs'],
        ['Literature', 'Adabiyot'],
        ['Architecture', 'Arxitektura'],
        ['Cuisine', 'Oshxona'],
        ['Language', 'Til'],
        ['Dialect', 'Lehja'],
        ['Ethnic', 'Millat'],
        ['National', 'Milliy'],
        ['Global', 'Global'],
        ['Diverse', 'Xilma-xil'],
      ],
      reading: {
        't': "Uzbekistan has rich culture.\nWe have many traditions and customs.\nNavruz is our national celebration.\nPeople cook special food on that day.\nMusic and dance are important parts of our culture.",
        'q': "Navruz nima?",
        'o': ['Food', 'Celebration', 'Music', 'Dance'],
        'c': 1,
      },
      listening: "Navruz is our national celebration.",
      writing: "Navruz bizning milliy bayramimiz.",
      writingSample: "Navruz is our national celebration.",
      speaking: "Talk about your culture.",
      grammar: "Madaniyat - Culture | An'ana - Tradition",
    ),
    // B2 Level
    Lesson(
      id: 31,
      level: 'B2',
      title: 'Present Perfect',
      vocab: [
        ['Have been', '...ganman'],
        ['Have done', '...qilganman'],
        ['Have seen', "ko'rganman"],
        ['Have bought', 'sotib olganman'],
        ['Have eaten', 'yeganman'],
        ['Have visited', "tashrif buyurganman"],
        ['Have learned', "o'rganganman"],
        ['Have traveled', 'sayohat qilganman'],
        ['Have met', "uchratganman"],
        ['Have read', "o'qiganman"],
        ['Already', 'Allaqachon'],
        ['Just', 'Endigina'],
        ['Yet', 'Hali'],
        ['Ever', 'Hech qachon'],
        ['Never', 'Hech qachon'],
        ['Since', '...dan beri'],
        ['For', '... davomida'],
        ['Recently', 'Yaqinda'],
        ['So far', 'Hozirgacha'],
        ['Up to now', 'Shu vaqtgacha'],
        ['Countless', "Sanash mumkin bo'lmagan"],
        ['Experience', 'Tajriba'],
        ['Lifetime', 'Umr'],
        ['Achievement', 'Yutuq'],
        ['Milestone', "Yurish nuqtasi"],
      ],
      reading: {
        't': "I have visited many countries.\nI have been to Turkey, Russia, and China.\nI have never been to America.\nHave you ever been to Europe?\nI have traveled more than 10,000 kilometers.",
        'q': "U qaysi mamlakatlarga borgan?",
        'o': ['America', 'Europe', 'Turkey, Russia, China', 'Japan'],
        'c': 2,
      },
      listening: "I have visited many countries.",
      writing: "Men ko'p mamlakatlarga tashrif buyurdim.",
      writingSample: "I have visited many countries.",
      speaking: "Talk about life experiences.",
      grammar: "Present Perfect - HAVE/HAS + V3 | TAJRIBA",
    ),
    Lesson(
      id: 32,
      level: 'B2',
      title: 'Relative Clauses',
      vocab: [
        ['Who', '... kim'],
        ['Which', '... qaysi'],
        ['That', '... (o\'ziga xos)'],
        ['Where', '... qayerda'],
        ['When', '... qachon'],
        ['Whose', '... ning'],
        ['Whom', '... kimni'],
        ['Which', '... nima'],
        ['This', 'Bu'],
        ['That', 'U'],
        ['These', 'Bular'],
        ['Those', 'Ular'],
        ['Person', 'Shaxs'],
        ['Place', 'Joy'],
        ['Thing', 'Narsa'],
        ['Time', 'Vaqt'],
        ['Reason', 'Sabab'],
        ['Way', 'Yo\'l'],
        ['Method', 'Usul'],
        ['System', 'Tizim'],
        ['Process', 'Jarayon'],
        ['Result', 'Natija'],
        ['Example', 'Misol'],
        ['Definition', 'Ta\'rif'],
        ['Description', 'Tavsif'],
      ],
      reading: {
        't': "The man who lives next door is a doctor.\nThe book that I read was interesting.\nThe city where I was born is Tashkent.\nThe day when I graduated was special.\nThe girl whose phone rang is my friend.",
        'q': "Qo'shni nima qiladi?",
        'o': ['Teacher', 'Doctor', 'Driver', 'Engineer'],
        'c': 1,
      },
      listening: "The man who lives next door is a doctor.",
      writing: "Qo'shni yashovchi erkak shifokor.",
      writingSample: "The man who lives next door is a doctor.",
      speaking: "Describe people using relative clauses.",
      grammar: "WHO / WHICH / THAT / WHERE / WHEN",
    ),
    Lesson(
      id: 33,
      level: 'B2',
      title: 'Modals of Deduction',
      vocab: [
        ['Must be', 'Albatta ...'],
        ['Might be', 'Ehtimol ...'],
        ['Could be', 'Mumkin ...'],
        ['Can\'t be', 'Bo\'lishi mumkin emas'],
        ['May be', 'Ehtimol ...'],
        ['Probably', 'Ehtimol'],
        ['Certainly', 'Albatta'],
        ['Definitely', 'Aniq'],
        ['Obviously', 'Ravshan'],
        ['Apparently', 'Ko\'rinadi'],
        ['Evidence', 'Dalil'],
        ['Proof', 'Isbot'],
        ['Possibility', 'Imkoniyat'],
        ['Probability', 'Ehtimollik'],
        ['Certainty', 'Ishonchlilik'],
        ['Uncertainty', 'Shubha'],
        ['Suspect', 'Shubhalanmoq'],
        ['Guess', 'Taxmin qilmoq'],
        ['Assume', 'Taxmin qilmoq'],
        ['Conclude', 'Xulosa qilmoq'],
        ['Deduce', 'Xulosa chiqarmoq'],
        ['Infer', 'Anglamoq'],
        ['Imply', 'Anglatmoq'],
        ['Suggest', 'Taklif qilmoq'],
        ['Recommend', 'Tavsiya qilmoq'],
      ],
      reading: {
        't': "She must be at home.\nHe can't be a doctor.\nThey might be on holiday.\nYou could be right.\nIt may be true.",
        'q': "U uyda bo'lishi mumkinmi?",
        'o': ['Yes, definitely', 'No, impossible', 'Maybe', 'Unknown'],
        'c': 2,
      },
      listening: "She must be at home.",
      writing: "U uyda bo'lishi kerak.",
      writingSample: "She must be at home.",
      speaking: "Make deductions about situations.",
      grammar: "MUST / MIGHT / COULD / CAN'T + BE",
    ),
    Lesson(
      id: 34,
      level: 'B2',
      title: 'Wish / If Only',
      vocab: [
        ['I wish', 'Men xohlayman'],
        ['If only', 'Faqat ... bo\'lsa'],
        ['I had', 'Men ... bo\'lganida'],
        ['I were', 'Men ... bo\'lganida'],
        ['I could', 'Men ... qila olganida'],
        ['I would', 'Men ... qilgan bo\'lardim'],
        ['Regret', "Pushaymonlik"],
        ['Hoping', 'Umid qilmoq'],
        ['Dreaming', 'Orzu qilmoq'],
        ['Fantasy', 'Fantaziya'],
        ['Reality', 'Haqiqat'],
        ['Mistake', 'Xato'],
        ['Chance', 'Imkoniyat'],
        ['Opportunity', 'Imkoniyat'],
        ['Experience', 'Tajriba'],
        ['Advice', 'Maslahat'],
        ['Suggestion', 'Taklif'],
        ['Recommendation', 'Tavsiya'],
        ['Decision', 'Qaror'],
        ['Choice', 'Tanlov'],
        ['Result', 'Natija'],
        ['Consequence', 'Oqibat'],
        ['Success', 'Muvaffaqiyat'],
        ['Failure', "Muvaffaqiyatsizlik"],
        ['Achievement', 'Yutuq'],
      ],
      reading: {
        't': "I wish I had more time.\nI wish I were taller.\nIf only I could speak English fluently.\nI wish I had studied harder.\nIf only I had known the answer.",
        'q': "U nima xohlaydi?",
        'o': ['More money', 'More time', 'More friends', 'More food'],
        'c': 1,
      },
      listening: "I wish I had more time.",
      writing: "Men ko'p vaqtim bo'lganini xohlayman.",
      writingSample: "I wish I had more time.",
      speaking: "Express wishes and regrets.",
      grammar: "WISH + Past Perfect / WERE / COULD",
    ),
    Lesson(
      id: 35,
      level: 'B2',
      title: 'Advanced Conditionals',
      vocab: [
        ['If I had known', 'Agar bilgan bo\'lsam'],
        ['If I were you', 'Agar men sizning o\'rnimda'],
        ['Unless', 'Agar ...masa'],
        ['Provided that', 'Agar ...lsa'],
        ['In case', 'Agar ...lsa'],
        ['Even if', 'Hattoki ... bo\'lsa ham'],
        ['As long as', 'Shartki'],
        ['Suppose that', 'Agar deylik'],
        ['Imagine that', 'Tasavvur qiling'],
        ['Assuming that', 'Taxmin qilamiz'],
        ['On condition that', 'Shart bilan'],
        ['Otherwise', 'Aks holda'],
        ['Or else', 'Yoki ...'],
        ['So that', 'Shuning uchun'],
        ['In order that', 'Maqsadida'],
        ['Whether', '... bo\'lsa ham'],
        ['However', 'Qanday bo\'lsa ham'],
        ['Whatever', 'Qanday bo\'lsa ham'],
        ['Whenever', 'Qachon bo\'lsa ham'],
        ['Wherever', 'Qayerda bo\'lsa ham'],
        ['Whoever', 'Kim bo\'lsa ham'],
        ['Scenario', 'Stsenariy'],
        ['Outcome', 'Natija'],
        ['Possibility', 'Imkoniyat'],
        ['Probability', 'Ehtimollik'],
      ],
      reading: {
        't': "If I had studied harder, I would have passed.\nUnless you hurry, you will be late.\nEven if it rains, we will go.\nAs long as you study, you will succeed.\nSuppose you won the lottery, what would you do?",
        'q': "Agar u ko'proq o'qiganida nima bo'lardi?",
        'o': ['Failed', 'Passed', 'Left', 'Studied more'],
        'c': 1,
      },
      listening: "If I had studied harder, I would have passed.",
      writing: "Agar men ko'proq o'qigan bo'lsam, o'tgan bo'lar edim.",
      writingSample: "If I had studied harder, I would have passed.",
      speaking: "Talk about hypothetical past situations.",
      grammar: "Third Conditional - IF + HAD + V3, WOULD HAVE + V3",
    ),
    Lesson(
      id: 36,
      level: 'B2',
      title: 'Causative',
      vocab: [
        ['Have something done', '... qildirmoq'],
        ['Get something done', '... qildirmoq'],
        ['Make someone do', '... qildirmoq'],
        ['Let someone do', '... qildirmoq'],
        ['Repair', 'Tuzatmoq'],
        ['Fix', 'Tuzatmoq'],
        ['Build', 'Qurmoq'],
        ['Clean', 'Tozalamoq'],
        ['Paint', 'Bo\'yamoq'],
        ['Install', 'O\'rnatmoq'],
        ['Design', 'Loyihalashtirmoq'],
        ['Create', 'Yaratmoq'],
        ['Produce', 'Ishlab chiqarmoq'],
        ['Manufacture', 'Ishlab chiqarmoq'],
        ['Assemble', 'Yig\'moq'],
        ['Decorate', 'Bezatmoq'],
        ['Furnish', 'Jihozlamoq'],
        ['Arrange', 'Tartibga solmoq'],
        ['Organize', 'Tashkil qilmoq'],
        ['Manage', 'Boshqarmoq'],
        ['Supervise', 'Nazorat qilmoq'],
        ['Oversee', 'Nazorat qilmoq'],
        ['Contract', 'Shartnoma'],
        ['Service', 'Xizmat'],
        ['Maintenance', 'Texnik xizmat'],
      ],
      reading: {
        't': "I had my car repaired yesterday.\nShe got her hair cut at the salon.\nWe had the house painted last month.\nHe had his computer fixed.\nThey got the roof repaired.",
        'q': "Uning mashinasi nima bo'ldi?",
        'o': ['Sold', 'Repaired', 'Bought', 'Crashed'],
        'c': 1,
      },
      listening: "I had my car repaired yesterday.",
      writing: "Men mashinamni tuzartirdim.",
      writingSample: "I had my car repaired yesterday.",
      speaking: "Talk about services you use.",
      grammar: "HAVE/GET + OBJECT + PAST PARTICIPLE",
    ),
    // C1 Level
    Lesson(
      id: 37,
      level: 'C1',
      title: 'Inversion',
      vocab: [
        ['Never have I', 'Hech qachon men'],
        ['Rarely', 'Kamdan-kam'],
        ['Seldom', 'Kamdan-kam'],
        ['Hardly ever', 'Deyarli hech qachon'],
        ['Not only', 'Faqat emas'],
        ['But also', 'Balki'],
        ['Neither', 'Na'],
        ['Nor', 'Na'],
        ['No sooner', "Tezroq"],
        ['Hardly when', "Zoir etmasdan"],
        ['Scarcely', 'Garchi'],
        ['Little', 'Kam'],
        ['Only then', 'Faqat keyin'],
        ['Only when', 'Faqat qachon'],
        ['Only after', 'Faqat keyin'],
        ['Not until', '...gacha emas'],
        ['At no time', 'Hech qachon'],
        ['In no way', "Hech qanday"],
        ['Under no circumstances', "Hech qanday holatda"],
        ['On no account', "Hech qanday"],
        ['So fast', 'Shuncha tez'],
        ['Such a', 'Shunday'],
        ['Importantly', 'Muhim'],
        ['Consequently', 'Natijada'],
        ['Furthermore', 'Shuningdek'],
      ],
      reading: {
        't': "Never have I seen such a beautiful sunset.\nNot only did he pass, but he also got the highest score.\nHardly had I arrived when it started to rain.\nOnly then did I realize my mistake.\nLittle did she know what was about to happen.",
        'q': "U nima ko'rdi?",
        'o': ['Sunrise', 'Beautiful sunset', 'Rain', 'Snow'],
        'c': 1,
      },
      listening: "Never have I seen such a beautiful sunset.",
      writing: "Men hech qachon bunday go'zal quyosh botishini ko'rmagan edim.",
      writingSample: "Never have I seen such a beautiful sunset.",
      speaking: "Use inversions for emphasis.",
      grammar: "Inversion - So'z tartibini o'zgartirish | NEVER / RARELY / NOT ONLY",
    ),
    Lesson(
      id: 38,
      level: 'C1',
      title: 'Advanced Conditionals',
      vocab: [
        ['Were to', '... bo\'lsa'],
        ['Suppose', 'Agar deylik'],
        ['Imagine', 'Tasavvur qiling'],
        ['Had I known', 'Agar bilgan bo\'lsam'],
        ['Should you need', 'Agar kerak bo\'lsa'],
        ['Were you to', 'Agar siz ... bo\'lsangiz'],
        ['Provided that', 'Agar ...lsa'],
        ['On condition that', 'Shart bilan'],
        ['In the event that', 'Agar ...lsa'],
        ['Assuming that', 'Taxmin qilamiz'],
        ['Given that', '... hisobga olib'],
        ['Seeing that', '... ko\'rib'],
        ['Now that', 'Endi ...'],
        ['In case', 'Agar ...lsa'],
        ['Unless', 'Agar ...masa'],
        ['Regardless', "Qanday bo'lsa ham"],
        ['Irrespective', "Qanday bo'lsa ham"],
        ['Whether or not', "... bo'lsa ham bo'lmasin"],
        ['Despite', '...ga qaramay'],
        ['In spite of', '...ga qaramay'],
        ['Notwithstanding', '...ga qaramay'],
        ['Nonetheless', 'Shunga qaramay'],
        ['Nevertheless', 'Shunga qaramay'],
        ['Consequently', 'Shuning uchun'],
        ['Therefore', 'Shuning uchun'],
      ],
      reading: {
        't': "Were I you, I would study harder.\nHad I known about the meeting, I would have attended.\nShould you need any help, please call me.\nSuppose you were the president, what would you change?\nGiven that it's raining, we should stay inside.",
        'q': "Agar u prezident bo'lsa, nima qilardi?",
        'o': ['Nothing', 'Change things', 'Travel', 'Sleep'],
        'c': 1,
      },
      listening: "Were I you, I would study harder.",
      writing: "Agar men sizning o'rnimda bo'lsam, ko'proq o'qigan bo'lar edim.",
      writingSample: "Were I you, I would study harder.",
      speaking: "Express advanced hypotheticals.",
      grammar: "WERE TO / HAD I KNOWN / SHOULD YOU NEED",
    ),
    Lesson(
      id: 39,
      level: 'C1',
      title: 'Cleft Sentences',
      vocab: [
        ['It was ... who', '... edi'],
        ['It was ... that', '... edi'],
        ['The reason is', 'Sababi'],
        ['What I mean is', 'Men nima demoqchiman'],
        ['The thing is', 'Mammot shundaki'],
        ['All I want', 'Men nima istayman'],
        ['What happened', 'Nima bo\'ldi'],
        ['The problem is', 'Muammo shundaki'],
        ['The truth is', 'Haqiqat shundaki'],
        ['The fact is', 'Fakt shundaki'],
        ['What matters is', 'Muhim narsa'],
        ['The point is', 'Nuqta shundaki'],
        ['The issue is', 'Muammo shundaki'],
        ['The matter is', 'Mammot shundaki'],
        ['The outcome is', 'Natija shundaki'],
        ['The result is', 'Natija shundaki'],
        ['What I think is', 'Men nima o\'ylayman'],
        ['What I believe is', 'Men nima ishonaman'],
        ['What I know is', 'Men nima bilaman'],
        ['What I saw was', 'Men nima ko\'rdim'],
        ['What I heard was', 'Men nima eshitdim'],
        ['Emphasis', 'E\'tibor'],
        ['Focus', 'Diqqat'],
        ['Highlight', 'Ajratib ko\'rsatish'],
        ['Stress', 'Urg\'u'],
      ],
      reading: {
        't': "It was Ali who broke the window.\nIt was yesterday that I met her.\nThe reason I am late is the traffic.\nWhat I need is more time.\nThe thing is, I don't have enough money.",
        'q': "Derazani kim sindirdi?",
        'o': ['Tom', 'Ali', 'John', 'David'],
        'c': 1,
      },
      listening: "It was Ali who broke the window.",
      writing: "Derazani sindirgan Ali edi.",
      writingSample: "It was Ali who broke the window.",
      speaking: "Use cleft sentences for emphasis.",
      grammar: "IT WAS/WERE ... WHO/THAT | WHAT I NEED IS ...",
    ),
    Lesson(
      id: 40,
      level: 'C1',
      title: 'Advanced Passive',
      vocab: [
        ['It is said that', "Aytilishicha"],
        ['It is believed that', "Ishonilishicha"],
        ['It is reported that', 'Hisobot berilishicha'],
        ['It is thought that', "O'ylashishicha"],
        ['It is known that', "Ma'lumki"],
        ['It is considered that', "Hisoblanishicha"],
        ['It is alleged that', 'Da\'vo qilinishicha'],
        ['It is claimed that', "Da'vo qilinishicha"],
        ['It is assumed that', "Taxmin qilinishicha"],
        ['It is suspected that', "Shubha qilinishicha"],
        ['It is alleged that', "Aytilishicha"],
        ['It is rumored that', "Mish-mish bo'lishicha"],
        ['It is predicted that', "Bashorat qilinishicha"],
        ['It is estimated that', "Hisoblashicha"],
        ['It is projected that', "Rejalashtirilishicha"],
        ['It is expected that', "Kutilishicha"],
        ['It is hoped that', "Umid qilinishicha"],
        ['It is feared that', "Qo'rqilishicha"],
        ['It is noticed that', "Diqqatga olinishicha"],
        ['It is observed that', "Kuzatilishicha"],
        ['It is suggested that', "Taklif qilinishicha"],
        ['It is recommended that', "Tavsiya qilinishicha"],
        ['It is decided that', "Qaror qilinishicha"],
        ['It is agreed that', "Kelishilishicha"],
        ['It is confirmed that', "Tasdiqlanishicha"],
      ],
      reading: {
        't': "It is said that English is the global language.\nIt is believed that exercise improves health.\nIt is reported that the economy is growing.\nIt is known that practice makes perfect.\nIt is estimated that 1.5 billion people speak English.",
        'q': "Ingliz tili global til ekanligi nima deyiladi?",
        'o': ['Rumored', 'Said', 'Feared', 'Suspected'],
        'c': 1,
      },
      listening: "It is said that English is the global language.",
      writing: "Ingliz tili global til ekanligi aytiladi.",
      writingSample: "It is said that English is the global language.",
      speaking: "Report opinions using passive.",
      grammar: "IT IS SAID/BELIEVED/THOUGHT THAT ...",
    ),
  ];
}
